modLoader="javafml" #mandatory

loaderVersion="[32,36,)"

license="MIT"

[[mods]]
# The modid of the mod
modId="rpmtw_update_mod"

version = "1.0.5"
# A display name for the mod
displayName="RpmtwUpdateMod"

authors="SiongSng" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
This is a mod that can automatically download and load the RPMTW Traditional Chinese resource pack.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.rpmtw_update_mod]] #optional
   # the modid of the dependency
   modId="forge" #mandatory
   # Does this dependency have to exist - if not, ordering below must be specified
   mandatory=true #mandatory
   # The version range of the dependency
   versionRange="[32,36,)" #mandatory
   # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
   ordering="NONE"
   # Side this dependency is applied on - BOTH, CLIENT or SERVER
   side="BOTH"
# Here's another dependency
[[dependencies.rpmtw_update_mod]]
   modId="minecraft"
   mandatory=true
   # This version range declares a minimum of the current minecraft version up to but not including the next major version
   versionRange="[1.16.1,1.16.5)"
   ordering="NONE"
   side="BOTH"
