name: Build

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get github short hash
        id: github_short_hash
        run: echo "::set-output name=result::$(git rev-parse --short "${{ github.sha }}")"
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: |
          cd ${{ github.workspace }}
          chmod +x gradlew
          sh ./gradlew build
      - name: Upload artifacts (fabric)
        uses: actions/upload-artifact@v3
        with:
          name: 1.18.2-${{ steps.github_short_hash.outputs.result }}-fabric.zip
          path: ${{ github.workspace }}/fabric/build/libs/rpmtw-platform-mod-1.18-2.0.0.jar
      - name: Upload artifacts (forge)
        uses: actions/upload-artifact@v3
        with:
          name: 1.18.2-${{ steps.github_short_hash.outputs.result }}-forge.zip
          path: ${{ github.workspace }}/forge/build/libs/rpmtw-platform-mod-1.18-2.0.0.jar