name: Build

on:
  push:
    branches:
      - 1.18.1
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Build with Gradle
        run: |
          cd ${{ github.workspace }}
          chmod +x gradlew
          sh ./gradlew build
      - name: Upload artifacts (fabric)
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifact (Fabric).zip
          path: ${{ github.workspace }}/fabric/build/libs/
      - name: Upload artifacts (forge)
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifact (Forge).zip
          path: ${{ github.workspace }}/forge/build/libs/