# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Forge-Build-116:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
         ${{ github.workspace }}/1.16-forge
         ./gradlew build
    - name: "Upload Artifact"
      uses: actions/upload-artifact@v1
      with:
        name: RPMTWUpdateMod-1.16-Forge-${{ github.run_number }}
        path: ${{ github.workspace }}/1.16-forge/build/libs
        
  Fabric-Build-116:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
       cd ${{ github.workspace }}/1.16-Fabric
       ./gradlew build
    - name: "Upload Artifact"
      uses: actions/upload-artifact@v1
      with:
        name: RPMTWUpdateMod-1.16-fabric-${{ github.run_number }}
        path: ${{ github.workspace }}/1.16-fabric/build/libs

