name: Build Release

on:
  release:
    types:
      - published

jobs:
  Forge-Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Build with Gradle
        run: |
          cd ${{ github.workspace }}/Forge
          chmod +x gradlew
          sh ./gradlew build
      - name: Upload artifacts to Modrinth, Curseforge and GitHub
        uses: Kir-Antipov/mc-publish@v2.0
        with:
          curseforge-id: 461500
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files-primary: ${{ github.workspace }}/Forge/build/libs/!(*-@(dev|sources)).jar
          version-type: beta
          name: ${{ github.event.release.name }} (Forge)
          loaders: forge
          version-resolver: latest
          java: |
            8
